import { useEffect, useRef, useId, memo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import mermaid from 'mermaid';

/**
 * Renders a mermaid diagram from source text.
 * Detects dark mode from the <html> element and picks the matching mermaid theme.
 * Note: mermaid.render() returns trusted SVG generated by the mermaid library itself
 * (not user content), so setting innerHTML here is safe.
 */
function MermaidBlock({ chart }: { chart: string }) {
  const containerRef = useRef<HTMLDivElement>(null);
  const id = useId().replace(/:/g, '_');

  useEffect(() => {
    if (!containerRef.current || !chart.trim()) return;
    let cancelled = false;

    const isDark = document.documentElement.classList.contains('dark');
    mermaid.initialize({
      startOnLoad: false,
      theme: isDark ? 'dark' : 'default',
      securityLevel: 'loose',
      fontFamily: 'inherit',
    });

    const container = containerRef.current;

    (async () => {
      try {
        const { svg } = await mermaid.render(`mermaid_${id}`, chart.trim());
        if (!cancelled && container) {
          // SVG is generated by mermaid library (trusted output, not user HTML)
          container.innerHTML = svg;
        }
      } catch {
        if (!cancelled && container) {
          container.textContent = chart;
          container.classList.add('whitespace-pre-wrap', 'text-xs', 'text-muted-foreground');
        }
      }
    })();

    return () => { cancelled = true; };
  }, [chart, id]);

  return (
    <div
      ref={containerRef}
      className="mb-2 flex justify-center overflow-x-auto rounded-md bg-muted/30 p-4 last:mb-0 [&_svg]:max-w-full"
    />
  );
}

function MarkdownInner({ children }: { children: string }) {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        h1: ({ children: c }) => (
          <h1 className="mb-3 mt-4 text-lg font-bold first:mt-0">{c}</h1>
        ),
        h2: ({ children: c }) => (
          <h2 className="mb-2 mt-3 text-base font-semibold first:mt-0">{c}</h2>
        ),
        h3: ({ children: c }) => (
          <h3 className="mb-2 mt-3 text-sm font-semibold first:mt-0">{c}</h3>
        ),
        h4: ({ children: c }) => (
          <h4 className="mb-1 mt-2 text-sm font-medium first:mt-0">{c}</h4>
        ),
        p: ({ children: c }) => <p className="mb-2 last:mb-0">{c}</p>,
        ul: ({ children: c }) => (
          <ul className="mb-2 ml-4 list-disc space-y-1 last:mb-0">{c}</ul>
        ),
        ol: ({ children: c }) => (
          <ol className="mb-2 ml-4 list-decimal space-y-1 last:mb-0">{c}</ol>
        ),
        li: ({ children: c }) => <li>{c}</li>,
        code: ({ className, children: c, ...props }) => {
          const match = /language-(\w+)/.exec(className ?? '');
          const lang = match?.[1];

          // Mermaid diagrams
          if (lang === 'mermaid') {
            return <MermaidBlock chart={String(c).replace(/\n$/, '')} />;
          }

          // Block code
          if (lang) {
            return (
              <pre className="mb-2 overflow-x-auto rounded-md bg-muted p-3 last:mb-0">
                <code className="text-xs">{c}</code>
              </pre>
            );
          }

          // Inline code
          return (
            <code className="rounded bg-muted px-1 py-0.5 text-xs" {...props}>
              {c}
            </code>
          );
        },
        pre: ({ children: c }) => <>{c}</>,
        table: ({ children: c }) => (
          <div className="mb-2 overflow-x-auto rounded-md border last:mb-0">
            <table className="w-full border-collapse text-xs">{c}</table>
          </div>
        ),
        thead: ({ children: c }) => (
          <thead className="border-b bg-muted/50">{c}</thead>
        ),
        tbody: ({ children: c }) => <tbody>{c}</tbody>,
        tr: ({ children: c }) => <tr className="border-b last:border-b-0">{c}</tr>,
        th: ({ children: c }) => (
          <th className="px-3 py-2 text-left text-xs font-semibold">{c}</th>
        ),
        td: ({ children: c }) => (
          <td className="px-3 py-2 text-xs">{c}</td>
        ),
        blockquote: ({ children: c }) => (
          <blockquote className="mb-2 border-l-2 border-muted-foreground/30 pl-3 italic last:mb-0">
            {c}
          </blockquote>
        ),
        strong: ({ children: c }) => <strong className="font-semibold">{c}</strong>,
        em: ({ children: c }) => <em>{c}</em>,
        hr: () => <hr className="my-3 border-border" />,
        a: ({ href, children: c }) => (
          <a
            href={href}
            className="text-primary underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            {c}
          </a>
        ),
        // GFM: strikethrough
        del: ({ children: c }) => <del className="text-muted-foreground">{c}</del>,
        // GFM: task list checkboxes
        input: (props) => {
          if (props.type === 'checkbox') {
            return (
              <input
                type="checkbox"
                checked={props.checked}
                disabled
                className="mr-1.5 align-middle"
              />
            );
          }
          return <input {...props} />;
        },
      }}
    >
      {children}
    </ReactMarkdown>
  );
}

export const Markdown = memo(MarkdownInner);
