import { Database } from 'lucide-react';
import { PageHeader } from '@/components/shared/page-header';
import { EmptyState } from '@/components/shared/empty-state';

export function ResourcesPage() {
  return (
    <div className="flex flex-1 flex-col gap-8">
      <PageHeader
        title="Resources"
        subtitle="Files, datasets, and generated outputs."
      />
      <EmptyState
        icon={Database}
        title="No resources"
        description="The resource registry tracks all files, datasets, and outputs generated by agents during task execution."
      />
    </div>
  );
}
